-- ----------------------------
-- OMS 海柜订单第一版：列表、新增、详情
-- ----------------------------

CREATE TABLE IF NOT EXISTS `biz_root` (
  `id` bigint NOT NULL COMMENT '业务主线ID',
  `tenant_id` varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `company_id` bigint NOT NULL COMMENT '主体ID',
  `warehouse_id` bigint DEFAULT NULL COMMENT '当前主仓库ID',
  `root_no` varchar(64) NOT NULL COMMENT '业务主线编号',
  `root_type` varchar(30) NOT NULL COMMENT '业务主线类型',
  `source_module` varchar(30) NOT NULL COMMENT '来源模块',
  `source_order_id` bigint NOT NULL COMMENT '来源订单ID',
  `source_order_no` varchar(64) NOT NULL COMMENT '来源订单号',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `customer_name` varchar(128) DEFAULT NULL COMMENT '客户名称',
  `channel_id` bigint DEFAULT NULL COMMENT '渠道ID',
  `business_type_id` bigint DEFAULT NULL COMMENT '业务类型ID',
  `current_module` varchar(30) DEFAULT NULL COMMENT '当前模块',
  `current_node` varchar(64) DEFAULT NULL COMMENT '当前节点编码',
  `current_node_name` varchar(128) DEFAULT NULL COMMENT '当前节点名称',
  `current_node_time` datetime DEFAULT NULL COMMENT '当前节点时间',
  `root_status` varchar(30) NOT NULL DEFAULT 'RUNNING' COMMENT '主线状态',
  `exception_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否异常',
  `exception_count` int NOT NULL DEFAULT 0 COMMENT '异常数',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `complete_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_root_no_tenant` (`root_no`, `tenant_id`),
  KEY `idx_source_order` (`source_module`, `source_order_id`),
  KEY `idx_company_warehouse` (`company_id`, `warehouse_id`),
  KEY `idx_root_status` (`tenant_id`, `root_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业务主线根';

CREATE TABLE IF NOT EXISTS `oms_container_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `company_id` bigint NOT NULL COMMENT '主体ID',
  `customer_id` bigint NOT NULL COMMENT '客户ID',
  `customer_name` varchar(128) NOT NULL COMMENT '客户名称',
  `channel_id` bigint DEFAULT NULL COMMENT '渠道ID',
  `business_type_id` bigint DEFAULT NULL COMMENT '业务类型ID',
  `owner_user_id` bigint DEFAULT NULL COMMENT '负责人ID',
  `owner_user_name` varchar(64) DEFAULT NULL COMMENT '负责人名称',
  `customer_service_id` bigint DEFAULT NULL COMMENT '客服ID',
  `customer_service_name` varchar(64) DEFAULT NULL COMMENT '客服名称',
  `warehouse_id` bigint NOT NULL COMMENT '入库仓库ID',
  `inbound_warehouse_name` varchar(128) DEFAULT NULL COMMENT '入库仓库名称',
  `container_order_no` varchar(64) NOT NULL COMMENT '海柜订单号',
  `order_source` varchar(32) NOT NULL DEFAULT 'MANUAL' COMMENT '订单来源',
  `container_no` varchar(32) NOT NULL COMMENT '柜号',
  `container_type` varchar(30) NOT NULL COMMENT '柜型',
  `seal_no` varchar(64) DEFAULT NULL COMMENT '封条号',
  `shipping_line_id` bigint DEFAULT NULL COMMENT '船公司ID',
  `shipping_line_name` varchar(128) DEFAULT NULL COMMENT '船公司名称',
  `vessel_name` varchar(128) DEFAULT NULL COMMENT '船名',
  `voyage_no` varchar(64) DEFAULT NULL COMMENT '航次',
  `route_code` varchar(64) DEFAULT NULL COMMENT '航线代码',
  `mbl_no` varchar(64) DEFAULT NULL COMMENT 'MBL',
  `hbl_no` varchar(64) DEFAULT NULL COMMENT 'HBL',
  `discharge_port_id` bigint DEFAULT NULL COMMENT '卸货港ID',
  `discharge_port_name` varchar(128) DEFAULT NULL COMMENT '卸货港名称',
  `terminal_id` bigint DEFAULT NULL COMMENT '码头ID',
  `terminal_name` varchar(128) DEFAULT NULL COMMENT '码头名称',
  `eta` datetime DEFAULT NULL COMMENT '预计到港',
  `ata` datetime DEFAULT NULL COMMENT '实际到港',
  `pickup_lfd` date DEFAULT NULL COMMENT '提柜LFD，仅日期',
  `empty_return_lfd` date DEFAULT NULL COMMENT '还柜LFD，仅日期',
  `terminal_release_status` varchar(30) NOT NULL DEFAULT 'UNKNOWN' COMMENT '码头释放状态',
  `hold_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否Hold',
  `hold_types` varchar(255) DEFAULT NULL COMMENT 'Hold类型，逗号分隔',
  `hold_remark` varchar(500) DEFAULT NULL COMMENT 'Hold备注',
  `exam_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否查验',
  `exam_types` varchar(255) DEFAULT NULL COMMENT '查验类型，逗号分隔',
  `exam_type` varchar(64) DEFAULT NULL COMMENT '查验类型',
  `exam_remark` varchar(500) DEFAULT NULL COMMENT '查验备注',
  `drayage_vendor_id` bigint DEFAULT NULL COMMENT '提柜供应商ID',
  `drayage_vendor_name` varchar(128) DEFAULT NULL COMMENT '提柜供应商名称',
  `pickup_appointment_no` varchar(64) DEFAULT NULL COMMENT '提柜预约号',
  `pickup_appointment_time` datetime DEFAULT NULL COMMENT '提柜预约时间',
  `actual_pickup_time` datetime DEFAULT NULL COMMENT '实际提柜时间',
  `pickup_remark` text DEFAULT NULL COMMENT '提柜备注',
  `expected_arrival_time` datetime DEFAULT NULL COMMENT '预计到仓时间',
  `actual_arrival_time` datetime DEFAULT NULL COMMENT '实际到仓时间',
  `container_location` varchar(128) DEFAULT NULL COMMENT '海柜Location',
  `arrival_remark` text DEFAULT NULL COMMENT '到仓备注',
  `devanning_no` varchar(64) DEFAULT NULL COMMENT '拆柜单号',
  `devanning_order_no` varchar(64) DEFAULT NULL COMMENT '拆柜单号',
  `devanning_warehouse_id` bigint DEFAULT NULL COMMENT '拆柜仓库ID',
  `expected_devanning_time` datetime DEFAULT NULL COMMENT '预计拆柜时间',
  `devanning_appointment_time` datetime DEFAULT NULL COMMENT '拆柜预约时间',
  `devanning_method` varchar(30) DEFAULT NULL COMMENT '拆柜方式',
  `loading_type` varchar(32) DEFAULT NULL COMMENT '装载类型',
  `sorting_method` varchar(32) DEFAULT NULL COMMENT '分货方式',
  `devanning_start_time` datetime DEFAULT NULL COMMENT '开始拆柜时间',
  `devanning_finish_time` datetime DEFAULT NULL COMMENT '拆柜完成时间',
  `devanning_remark` text DEFAULT NULL COMMENT '拆柜备注',
  `empty_return_location` varchar(128) DEFAULT NULL COMMENT '还柜地点',
  `empty_return_appointment_no` varchar(64) DEFAULT NULL COMMENT '还柜预约号',
  `empty_return_time` datetime DEFAULT NULL COMMENT '实际还柜时间',
  `empty_return_status` varchar(30) DEFAULT NULL COMMENT '还柜状态',
  `empty_return_remark` text DEFAULT NULL COMMENT '还柜备注',
  `pre_plan_truck_qty` decimal(12,0) DEFAULT 0 COMMENT '预排车数，关联预出单数量',
  `pre_plan_pallet_qty` decimal(12,0) DEFAULT 0 COMMENT '预排板数（历史兼容字段）',
  `pre_plan_cbm` decimal(12,3) DEFAULT 0 COMMENT '预排体积',
  `total_carton_qty` decimal(12,0) DEFAULT 0 COMMENT '总箱数',
  `total_pallet_qty` decimal(12,0) DEFAULT 0 COMMENT '总板数',
  `total_weight` decimal(12,3) DEFAULT 0 COMMENT '总重量kg',
  `total_cbm` decimal(12,3) DEFAULT 0 COMMENT '总体积CBM',
  `container_exception_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否海柜异常',
  `container_exception_type` varchar(128) DEFAULT NULL COMMENT '海柜异常类型',
  `container_exception_count` int NOT NULL DEFAULT 0 COMMENT '海柜异常数',
  `downstream_exception_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否下游异常',
  `downstream_exception_count` int NOT NULL DEFAULT 0 COMMENT '下游异常数',
  `container_status` varchar(30) NOT NULL DEFAULT 'PENDING_ACCEPT' COMMENT '海柜状态',
  `internal_remark` text DEFAULT NULL COMMENT '内部备注',
  `status` varchar(10) NOT NULL DEFAULT '0' COMMENT '启停状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_container_order_no_tenant` (`container_order_no`, `tenant_id`),
  KEY `idx_tenant_status` (`tenant_id`, `container_status`),
  KEY `idx_company_warehouse` (`company_id`, `warehouse_id`),
  KEY `idx_container_no` (`container_no`),
  KEY `idx_eta` (`eta`),
  KEY `idx_pickup_lfd` (`pickup_lfd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OMS海柜订单';

CREATE TABLE IF NOT EXISTS `oms_cargo_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `biz_root_id` bigint NOT NULL COMMENT '业务主线ID',
  `company_id` bigint NOT NULL COMMENT '主体ID',
  `warehouse_id` bigint NOT NULL COMMENT '入库仓库ID',
  `container_order_id` bigint DEFAULT NULL COMMENT '海柜订单ID',
  `container_order_no` varchar(64) DEFAULT NULL COMMENT '海柜订单号',
  `container_no` varchar(32) DEFAULT NULL COMMENT '柜号',
  `cargo_order_no` varchar(64) NOT NULL COMMENT '货物订单号',
  `customer_id` bigint NOT NULL COMMENT '客户ID',
  `customer_name` varchar(128) NOT NULL COMMENT '客户名称',
  `channel_id` bigint DEFAULT NULL COMMENT '渠道ID',
  `business_type_id` bigint DEFAULT NULL COMMENT '业务类型ID',
  `platform_code` varchar(64) DEFAULT NULL COMMENT '平台',
  `address_type` varchar(30) DEFAULT NULL COMMENT '地址类型',
  `warehouse_code` varchar(64) DEFAULT NULL COMMENT '仓库代码',
  `customer_service_id` bigint DEFAULT NULL COMMENT '客服ID',
  `customer_service_name` varchar(64) DEFAULT NULL COMMENT '客服名称',
  `fulfillment_status` varchar(30) NOT NULL DEFAULT 'PENDING_ACCEPT' COMMENT '履约状态',
  `billing_status` varchar(30) NOT NULL DEFAULT 'UNBILLED' COMMENT '账单状态',
  `pre_outbound_status` varchar(30) NOT NULL DEFAULT 'none' COMMENT '预出单状态',
  `shipment_codes` varchar(500) DEFAULT NULL COMMENT '货件编码聚合',
  `po_nos` varchar(500) DEFAULT NULL COMMENT 'PO号聚合',
  `marks` varchar(500) DEFAULT NULL COMMENT 'Mark/唛头聚合',
  `cargo_qty` decimal(12,0) DEFAULT NULL COMMENT '货件数量',
  `expected_box_qty` decimal(12,0) DEFAULT NULL COMMENT '预报箱数',
  `expected_pallet_qty` decimal(12,0) DEFAULT NULL COMMENT '预报板数',
  `expected_weight` decimal(12,3) DEFAULT NULL COMMENT '预报重量kg',
  `expected_cbm` decimal(12,3) DEFAULT NULL COMMENT '预报体积CBM',
  `earliest_dw_time` datetime DEFAULT NULL COMMENT '最早DW时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` varchar(10) NOT NULL DEFAULT '0' COMMENT '启停状态',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cargo_order_no_tenant` (`cargo_order_no`, `tenant_id`),
  KEY `idx_biz_root_id` (`biz_root_id`),
  KEY `idx_container_order_id` (`container_order_id`),
  KEY `idx_company_warehouse` (`company_id`, `warehouse_id`),
  KEY `idx_tenant_status` (`tenant_id`, `fulfillment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OMS货物订单';

CREATE TABLE IF NOT EXISTS `oms_cargo_order_shipment` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `cargo_order_id` bigint NOT NULL COMMENT '货物订单ID',
  `biz_root_id` bigint NOT NULL COMMENT '业务主线ID',
  `container_order_id` bigint DEFAULT NULL COMMENT '海柜订单ID',
  `cargo_order_no` varchar(64) DEFAULT NULL COMMENT '货物订单号',
  `shipment_code` varchar(64) NOT NULL COMMENT '货件编码',
  `po_no` varchar(64) DEFAULT NULL COMMENT 'PO号',
  `mark` varchar(128) DEFAULT NULL COMMENT 'Mark/唛头',
  `sku_summary` varchar(500) DEFAULT NULL COMMENT 'SKU摘要',
  `expected_qty` decimal(12,0) DEFAULT NULL COMMENT '预报数量',
  `expected_box_qty` decimal(12,0) DEFAULT NULL COMMENT '预报箱数',
  `expected_weight` decimal(12,3) DEFAULT NULL COMMENT '预报重量kg',
  `expected_cbm` decimal(12,3) DEFAULT NULL COMMENT '预报体积CBM',
  `dw_time` datetime DEFAULT NULL COMMENT '预计到仓时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_cargo_order_id` (`cargo_order_id`),
  KEY `idx_container_order_id` (`container_order_id`),
  KEY `idx_biz_root_id` (`biz_root_id`),
  KEY `idx_dw_time` (`dw_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OMS货物订单货件层';

CREATE TABLE IF NOT EXISTS `oms_container_cargo_order_rel` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `container_order_id` bigint NOT NULL COMMENT '海柜订单ID',
  `container_order_no` varchar(64) NOT NULL COMMENT '海柜订单号',
  `container_no` varchar(32) NOT NULL COMMENT '柜号',
  `cargo_order_id` bigint NOT NULL COMMENT '货物订单ID',
  `cargo_order_no` varchar(64) NOT NULL COMMENT '货物订单号',
  `relation_type` varchar(30) NOT NULL COMMENT '关系类型',
  `relation_status` varchar(30) NOT NULL DEFAULT 'ACTIVE' COMMENT '关系状态',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_container_cargo` (`container_order_id`, `cargo_order_id`),
  KEY `idx_cargo_order_id` (`cargo_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OMS海柜货物订单关系';

CREATE TABLE IF NOT EXISTS `oms_container_order_trace` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` varchar(20) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `container_order_id` bigint NOT NULL COMMENT '海柜订单ID',
  `container_order_no` varchar(64) NOT NULL COMMENT '海柜订单号',
  `container_no` varchar(32) DEFAULT NULL COMMENT '柜号',
  `status_from` varchar(30) DEFAULT NULL COMMENT '变更前状态',
  `status_to` varchar(30) NOT NULL COMMENT '变更后状态',
  `action` varchar(64) NOT NULL COMMENT '动作编码',
  `action_desc` varchar(200) DEFAULT NULL COMMENT '动作说明',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人名称',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_container_order_id` (`container_order_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OMS海柜订单轨迹';

INSERT IGNORE INTO sys_dict_type (dict_id, tenant_id, dict_name, dict_type, create_by, create_time, update_by, update_time, remark)
VALUES
(9003001, '000000', '海柜状态', 'oms_container_status', 1, NOW(), 1, NOW(), 'OMS海柜订单生命周期状态'),
(9003002, '000000', '柜型', 'oms_container_type', 1, NOW(), 1, NOW(), 'OMS海柜柜型'),
(9003003, '000000', '码头释放状态', 'oms_terminal_release_status', 1, NOW(), 1, NOW(), '码头释放/Hold状态');

INSERT IGNORE INTO sys_dict_data (dict_code, tenant_id, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, create_by, create_time, update_by, update_time, remark)
VALUES
(9003101, '000000', 1, '草稿', 'DRAFT', 'oms_container_status', '', 'default', 'N', 1, NOW(), 1, NOW(), NULL),
(9003102, '000000', 2, '待受理', 'PENDING_ACCEPT', 'oms_container_status', '', 'warning', 'Y', 1, NOW(), 1, NOW(), NULL),
(9003103, '000000', 3, '在途', 'IN_TRANSIT', 'oms_container_status', '', 'info', 'N', 1, NOW(), 1, NOW(), NULL),
(9003104, '000000', 4, '已到港', 'ARRIVED_PORT', 'oms_container_status', '', 'info', 'N', 1, NOW(), 1, NOW(), NULL),
(9003105, '000000', 5, 'HOLD中', 'HOLDING', 'oms_container_status', '', 'error', 'N', 1, NOW(), 1, NOW(), NULL),
(9003106, '000000', 6, '查验中', 'EXAMINING', 'oms_container_status', '', 'warning', 'N', 1, NOW(), 1, NOW(), NULL),
(9003107, '000000', 7, '已可提', 'AVAILABLE_FOR_PICKUP', 'oms_container_status', '', 'success', 'N', 1, NOW(), 1, NOW(), NULL),
(9003108, '000000', 8, '已预约提柜', 'PICKUP_APPOINTED', 'oms_container_status', '', 'info', 'N', 1, NOW(), 1, NOW(), NULL),
(9003109, '000000', 9, '已提柜', 'PICKED_UP', 'oms_container_status', '', 'success', 'N', 1, NOW(), 1, NOW(), NULL),
(9003110, '000000', 10, '已到仓', 'ARRIVED_WAREHOUSE', 'oms_container_status', '', 'success', 'N', 1, NOW(), 1, NOW(), NULL),
(9003111, '000000', 11, '拆柜中', 'DEVANNING', 'oms_container_status', '', 'warning', 'N', 1, NOW(), 1, NOW(), NULL),
(9003112, '000000', 12, '拆柜完成', 'DEVANNED', 'oms_container_status', '', 'success', 'N', 1, NOW(), 1, NOW(), NULL),
(9003113, '000000', 13, '已还柜', 'EMPTY_RETURNED', 'oms_container_status', '', 'success', 'N', 1, NOW(), 1, NOW(), NULL),
(9003114, '000000', 14, '已完成', 'COMPLETED', 'oms_container_status', '', 'success', 'N', 1, NOW(), 1, NOW(), NULL),
(9003115, '000000', 15, '已取消', 'CANCELLED', 'oms_container_status', '', 'default', 'N', 1, NOW(), 1, NOW(), NULL),
(9003201, '000000', 1, '20GP', '20GP', 'oms_container_type', '', 'default', 'N', 1, NOW(), 1, NOW(), NULL),
(9003202, '000000', 2, '40GP', '40GP', 'oms_container_type', '', 'default', 'N', 1, NOW(), 1, NOW(), NULL),
(9003203, '000000', 3, '40HQ', '40HQ', 'oms_container_type', '', 'default', 'Y', 1, NOW(), 1, NOW(), NULL),
(9003204, '000000', 4, '45HQ', '45HQ', 'oms_container_type', '', 'default', 'N', 1, NOW(), 1, NOW(), NULL),
(9003301, '000000', 1, '未知', 'UNKNOWN', 'oms_terminal_release_status', '', 'default', 'Y', 1, NOW(), 1, NOW(), NULL),
(9003302, '000000', 2, '已释放', 'RELEASED', 'oms_terminal_release_status', '', 'success', 'N', 1, NOW(), 1, NOW(), NULL),
(9003303, '000000', 3, 'HOLD中', 'HOLDING', 'oms_terminal_release_status', '', 'error', 'N', 1, NOW(), 1, NOW(), NULL);

-- 菜单与权限
INSERT IGNORE INTO sys_menu VALUES(3000, 'OMS', 0, 20, 'oms', NULL, '', 1, 0, 'M', '0', '0', '', 'appstore', 103, 1, NOW(), NULL, NULL, 'OMS业务目录');
INSERT IGNORE INTO sys_menu VALUES(3001, '海柜订单', 3000, 1, 'container-order', 'oms/container-order/index', '', 1, 0, 'C', '0', '0', 'oms:containerOrder:list', 'container', 103, 1, NOW(), NULL, NULL, '海柜订单菜单');
INSERT IGNORE INTO sys_menu VALUES(3010, '海柜订单查询', 3001, 1, '#', '', '', 1, 0, 'F', '0', '0', 'oms:containerOrder:query', '#', 103, 1, NOW(), NULL, NULL, '');
INSERT IGNORE INTO sys_menu VALUES(3011, '海柜订单新增', 3001, 2, '#', '', '', 1, 0, 'F', '0', '0', 'oms:containerOrder:add', '#', 103, 1, NOW(), NULL, NULL, '');
INSERT IGNORE INTO sys_menu VALUES(3012, '海柜订单修改', 3001, 3, '#', '', '', 1, 0, 'F', '0', '0', 'oms:containerOrder:edit', '#', 103, 1, NOW(), NULL, NULL, '');
INSERT IGNORE INTO sys_menu VALUES(3013, '海柜订单删除', 3001, 4, '#', '', '', 1, 0, 'F', '0', '0', 'oms:containerOrder:remove', '#', 103, 1, NOW(), NULL, NULL, '');
INSERT IGNORE INTO sys_menu VALUES(3014, '海柜订单导出', 3001, 5, '#', '', '', 1, 0, 'F', '0', '0', 'oms:containerOrder:export', '#', 103, 1, NOW(), NULL, NULL, '');
INSERT IGNORE INTO sys_menu VALUES(3015, '海柜状态动作', 3001, 6, '#', '', '', 1, 0, 'F', '0', '0', 'oms:containerOrder:updateStatus', '#', 103, 1, NOW(), NULL, NULL, '');
