-- ----------------------------
-- BASE-022 SKU管理
-- ----------------------------
CREATE TABLE `mdm_sku` (
  `id`                    bigint         NOT NULL                  COMMENT '主键（雪花ID）',
  `tenant_id`             varchar(20)    NOT NULL                  COMMENT '租户ID',
  `client_id`             bigint         NOT NULL                  COMMENT '所属客户ID（mdm_client.id）',
  `sku_code`              varchar(100)   NOT NULL                  COMMENT 'SKU编码（客户内唯一）',
  `sku_name`              varchar(200)   NOT NULL                  COMMENT 'SKU名称（中文）',
  `sku_name_en`           varchar(200)   DEFAULT NULL              COMMENT 'SKU名称（英文）',
  `barcode`               varchar(100)   DEFAULT NULL              COMMENT '条形码/UPC/EAN',
  `category_id`           bigint         DEFAULT NULL              COMMENT '品类ID（BASE-020，暂预留）',
  `brand`                 varchar(100)   DEFAULT NULL              COMMENT '品牌',
  `model`                 varchar(100)   DEFAULT NULL              COMMENT '型号',
  `color`                 varchar(50)    DEFAULT NULL              COMMENT '颜色',
  `size_spec`             varchar(100)   DEFAULT NULL              COMMENT '尺寸规格',
  `unit`                  varchar(20)    NOT NULL DEFAULT 'pcs'    COMMENT '计量单位',
  `length_cm`             decimal(8,2)   DEFAULT NULL              COMMENT '长(cm)',
  `width_cm`              decimal(8,2)   DEFAULT NULL              COMMENT '宽(cm)',
  `height_cm`             decimal(8,2)   DEFAULT NULL              COMMENT '高(cm)',
  `weight_kg`             decimal(8,3)   DEFAULT NULL              COMMENT '重量(kg)',
  `volume_cbm`            decimal(12,6)  DEFAULT NULL              COMMENT '体积(CBM，系统自动计算)',
  `package_length_cm`     decimal(8,2)   DEFAULT NULL              COMMENT '外箱长(cm)',
  `package_width_cm`      decimal(8,2)   DEFAULT NULL              COMMENT '外箱宽(cm)',
  `package_height_cm`     decimal(8,2)   DEFAULT NULL              COMMENT '外箱高(cm)',
  `package_weight_kg`     decimal(8,3)   DEFAULT NULL              COMMENT '外箱重(kg)',
  `is_fragile`            tinyint        NOT NULL DEFAULT 0        COMMENT '易碎（0=否，1=是）',
  `is_liquid`             tinyint        NOT NULL DEFAULT 0        COMMENT '液体',
  `is_battery`            tinyint        NOT NULL DEFAULT 0        COMMENT '含电池',
  `is_magnetic`           tinyint        NOT NULL DEFAULT 0        COMMENT '带磁',
  `is_dangerous`          tinyint        NOT NULL DEFAULT 0        COMMENT '危险品',
  `is_oversize`           tinyint        NOT NULL DEFAULT 0        COMMENT '超大件',
  `default_pkg_id`        bigint         DEFAULT NULL              COMMENT '默认包装规格ID（mdm_packaging.id）',
  `default_fee_codes`     json           DEFAULT NULL              COMMENT '默认作业费项（JSON数组，如["LABEL_FEE","QC_CHECK"]）',
  `declared_name_cn`      varchar(200)   DEFAULT NULL              COMMENT '申报品名（中文）',
  `declared_name_en`      varchar(200)   DEFAULT NULL              COMMENT '申报品名（英文）',
  `hs_code`               varchar(30)    DEFAULT NULL              COMMENT 'HS编码',
  `declared_value`        decimal(12,2)  DEFAULT NULL              COMMENT '申报价值',
  `declared_currency`     varchar(10)    DEFAULT NULL              COMMENT '申报货币代码',
  `origin_country_code`   varchar(10)    DEFAULT NULL              COMMENT '原产国代码',
  `image_url`             varchar(500)   DEFAULT NULL              COMMENT '商品主图URL',
  `status`                char(1)        NOT NULL DEFAULT '0'      COMMENT '状态（0=正常，1=禁用）',
  `remark`                varchar(500)   DEFAULT NULL              COMMENT '备注',
  `create_dept`     bigint         DEFAULT NULL                 COMMENT '创建部门',
  `create_by`             bigint         DEFAULT NULL              COMMENT '创建者',
  `create_time`           datetime       DEFAULT NULL              COMMENT '创建时间',
  `update_by`             bigint         DEFAULT NULL              COMMENT '更新者',
  `update_time`           datetime       DEFAULT NULL              COMMENT '更新时间',
  `del_flag`              bigint         DEFAULT 0                 COMMENT '逻辑删除（0=存在，1=删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_client_sku` (`tenant_id`, `client_id`, `sku_code`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_barcode` (`barcode`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SKU管理';
