-- YMS 第二批菜单（调度/门岗/H5/规则等），ID 7600~7699
-- 依赖：02-yms-menu.sql 已执行

SET NAMES utf8mb4;

INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`,
                           `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`,
                           `create_time`, `updater`, `update_time`, `deleted`)
VALUES
    (7600, '调度中心', '', 1, 4, 7500, 'dispatch-center', 'ep:operation', NULL, NULL, 0, b'1', b'1', b'1',
     'admin', NOW(), 'admin', NOW(), b'0'),
    (7601, '拆柜调度', 'yms:yard:view', 2, 1, 7600, 'devanning', 'ep:box',
     'yms/devanning/index', 'YmsDevanning', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7602, '装车调度', 'yms:yard:view', 2, 2, 7600, 'loading', 'ep:van',
     'yms/loading/index', 'YmsLoading', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7603, '任务管理', 'yms:yard:view', 2, 3, 7600, 'task', 'ep:list',
     'yms/task/index', 'YmsTask', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7604, '等待池', 'yms:waitingPool:list', 2, 4, 7600, 'waiting-pool', 'ep:timer',
     'yms/waiting-pool/index', 'YmsWaitingPool', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7605, '园区总览', 'yms:overview:view', 2, 5, 7600, 'overview', 'ep:data-board',
     'yms/overview/index', 'YmsOverview', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7606, '堆场地图', 'yms:yardMap:view', 2, 6, 7600, 'yard-map', 'ep:map-location',
     'yms/yard-map/index', 'YmsYardMap', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7610, '门岗作业', '', 1, 5, 7500, 'gate-ops', 'ep:monitor', NULL, NULL, 0, b'1', b'1', b'1',
     'admin', NOW(), 'admin', NOW(), b'0'),
    (7611, '统一Check-in', 'yms:gate:checkIn', 2, 1, 7610, 'gate-checkin', 'ep:upload',
     'yms/gate-checkin/index', 'YmsGateCheckin', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7612, 'Check-out', 'yms:gate:checkout', 2, 2, 7610, 'gate-check-out', 'ep:download',
     'yms/gate-check-out/index', 'YmsGateCheckOut', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7613, '在场列表', 'yms:gate:inYard', 2, 3, 7610, 'gate-in-yard', 'ep:van',
     'yms/gate-in-yard/index', 'YmsGateInYard', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7620, 'YardGo', 'yms:yardgo:list', 2, 6, 7500, 'yardgo', 'ep:cpu',
     'yms/yardgo/index', 'YmsYardgo', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7621, '异常中心', 'yms:exception:list', 2, 7, 7500, 'exception-center', 'ep:warning',
     'yms/exception-center/index', 'YmsExceptionCenter', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7622, '黑名单', 'yms:blacklist:list', 2, 8, 7500, 'blacklist', 'ep:circle-close',
     'yms/blacklist/index', 'YmsBlacklist', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7630, '预约规则', '', 1, 3, 7510, 'apt-rules', 'ep:setting', NULL, NULL, 0, b'1', b'1', b'1',
     'admin', NOW(), 'admin', NOW(), b'0'),
    (7631, '预约看板', 'yms:appointment:list', 2, 1, 7630, 'appointment-board', 'ep:calendar',
     'yms/appointment-board/index', 'YmsAppointmentBoard', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7632, '预约规则', 'yms:appointmentRule:list', 2, 2, 7630, 'appointment-rule', 'ep:setting',
     'yms/appointment-rule/index', 'YmsAppointmentRule', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7633, '时段模板', 'yms:slotTemplate:list', 2, 3, 7630, 'slot-template', 'ep:clock',
     'yms/slot-template/index', 'YmsSlotTemplate', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7634, '叫号规则', 'yms:callRule:list', 2, 4, 7630, 'call-rule', 'ep:bell',
     'yms/call-rule/index', 'YmsCallRule', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7640, 'H5签到', '', 1, 9, 7500, 'h5', 'ep:iphone', NULL, NULL, 0, b'1', b'1', b'1',
     'admin', NOW(), 'admin', NOW(), b'0'),
    (7641, '海柜司机H5', '', 2, 1, 7640, 'h5-driver-checkin', 'ep:cellphone',
     'yms/h5-driver-checkin/index', 'YmsH5DriverCheckin', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7642, '装车司机H5', '', 2, 2, 7640, 'h5-trailer-checkin', 'ep:cellphone',
     'yms/h5-trailer-checkin/index', 'YmsH5TrailerCheckin', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0'),
    (7643, 'H5任务执行', 'yms:internalTask:list', 2, 3, 7640, 'h5-task-execute', 'ep:cellphone',
     'yms/h5-task-execute/index', 'YmsH5TaskExecute', 0, b'1', b'0', b'1', 'admin', NOW(), 'admin', NOW(), b'0')
ON DUPLICATE KEY UPDATE
    `name` = VALUES(`name`), `permission` = VALUES(`permission`), `path` = VALUES(`path`),
    `component` = VALUES(`component`), `component_name` = VALUES(`component_name`),
    `updater` = 'admin', `update_time` = NOW(), `deleted` = b'0';
